Instance: example-drug-clarithromycin-25mg-granule-suspension
InstanceOf: MedicationKnowledge
Usage: #example
* meta.profile = "http://hl7.org/fhir/uv/order-catalog/StructureDefinition/DrugKnowledge"
* language = #en-US
* extension[0].url = "http://hl7.org/fhir/uv/order-catalog/StructureDefinition/CatalogReference"
* extension[0].valueReference = Reference(Composition/example-medication-catalog-header)
* code = $SCT#769316002 "Clarithromycin 25 mg/mL oral suspension"
* intendedJurisdiction[0].text = "Healthyland"
* name = "CLARITHROMYCINE GENERIC-LAB 25 mg/ml, granules for oral suspension"
* productType.text = "Generic product"
* indicationGuideline[0].indication[0].reference = Reference(ClinicalUseDefinition/example-bacterial-pharyngitis-indication)
* indicationGuideline[0].indication[1].reference = Reference(ClinicalUseDefinition/example-acute-otitis-media-indication)
* indicationGuideline[0].indication[2].reference = Reference(ClinicalUseDefinition/example-bacterial-sinusitis-indication)
* indicationGuideline[0].dosingGuideline[0].patientCharacteristic[0].type = $LOINC#30525-0 "Age"
* indicationGuideline[0].dosingGuideline[0].patientCharacteristic[0].valueRange.low = 0.5 'a' "years"
* indicationGuideline[0].dosingGuideline[0].patientCharacteristic[0].valueRange.high = 12 'a' "years"
* medicineClassification[0].type = $ATC#J01FA09 "Clarithromycin"
* medicineClassification[0].sourceUri = "https://www.whocc.no/atc/structure_and_principles/"
* medicineClassification[1].type = $SCT#346325008 "Medicinal product acting as antibacterial agent"
* medicineClassification[1].sourceUri = "https://confluence.ihtsdotools.org/display/DOCEG/SNOMED+CT+Editorial+Guide+-+Pharmaceutical+and+Biologic+Product"
* packaging[0].cost[0].effectiveDate.start = "2021-02-01"
* packaging[0].cost[0].type.text = "public price"
* packaging[0].cost[0].source = "Healthyland Drug Administration"
* packaging[0].cost[0].costMoney.value = 5.18
* packaging[0].cost[0].costMoney.currency = #EUR
* packaging[0].cost[1].effectiveDate.start = "2020-09-30"
* packaging[0].cost[1].effectiveDate.end = "2021-01-31"
* packaging[0].cost[1].type.text = "public price"
* packaging[0].cost[1].source = "Healthyland Drug Administration"
* packaging[0].cost[1].costMoney.value = 5.20
* packaging[0].cost[1].costMoney.currency = #EUR
* packaging[0].cost[2].effectiveDate.start = "2010-03-01"
* packaging[0].cost[2].type.text = "manufacturers' cost"
* packaging[0].cost[2].source = "Healthyland Drug Administration"
* packaging[0].cost[2].costMoney.value = 4.40
* packaging[0].cost[2].costMoney.currency = #EUR
* packaging[0].packagedProduct = Reference(PackagedProductDefinition/example-drug-package-clarithromycin)
* clinicalUseIssue[0] = Reference(ClinicalUseDefinition/example-allergy-contraindication)
                                                                                      // Does not exist in snapshot 1: * storageGuideline[0].stabilityDuration = 2 'a' "years"
* definitional.doseForm.coding[0] = $SCT#385029002 "Granules for oral suspension"
* definitional.doseForm.coding[1] = $EDQM#10113000 "Granules for oral suspension"
* definitional.intendedRoute = $SCT#26643006 "Oral route"
* definitional.ingredient[0].item.concept = $SCT#387487009 "Clarithromycin"
* definitional.ingredient[0].type = $V3ROLECLASS#ACTIB "active ingredient - basis of strength"
* definitional.ingredient[0].strengthRatio.numerator = 25 'mg' "milligram"
* definitional.ingredient[0].strengthRatio.denominator = 1 'mL' "milliliter"
* definitional.ingredient[1].item.concept = $SCT#11320009 "Sucrose"
* definitional.ingredient[1].type = $V3ROLECLASS#IACT "inactive ingredient"
